### ISSUE TITLE
Watcher not reporting events when used in docker.

### ISSUE THREAD

**Issue by azhar1038** [parcel-bundler/watcher#148]
I am using Windows 11 and trying to use `@parcel/watcher` in a docker container. I have mounted my files so that if I change anything locally it triggers the watcher but it is not working. Strangely if I change something in a mounted file through Docker Desktop, a `delete` and `create` events are fired.

Here is my `Dockerfile`
```Dockerfile
FROM node:alpine
WORKDIR /app
COPY ./package*.json /app
RUN npm install
COPY . .
CMD ["npm", "start"]
```

Here is my `docker-compose.yml`
```yaml
version: '3.8'
services:
  parcel:
    build: .
    volumes:
      - .:/app
      - nodeModules:/app/node_modules

volumes:
  nodeModules:
```

Same issue also happens with `chokidar` but `chokidar` has an option `usePolling` that uses polling to provide a workaround to this issue.
